#pragma once
#include <ntifs.h>
#include <ntddk.h>
#include <windef.h>
#include <strsafe.h>
#include <ntstrsafe.h>
#include <ntifs.h>
#include <intrin.h>
#include <cstdint>
#include <ntdef.h>
#include <utilities/cipher/kli.hpp>
#include <utilities/cipher/xorstr.hpp>
#include <utilities/time.hpp>
#include <utilities/process.hpp>
#include <utilities/filesystem.hpp>
#include <utilities/entry/entry.hpp>
